### ISSUE TITLE
Compile it on the Ubuntu workstation with g++(c++11 supported)

### ISSUE THREAD

**Issue by tamaswells** [IonizingRadiation/usefultools-for-vasp#4]
### 3. Try to `make` in the main working file and an executable binary `cgrad` is generated.
[cgrad.zip](https://github.com/IonizingRadiation/usefultools-for-vasp/files/2131670/cgrad.zip)

**Comment by Ionizing** [comment]
The invocation of `std::sort()` in `OUTCAR.cpp` requires `#include <altorithm>`. However in my mac environment, that `include` is not necessary.

I will add it to `OUTCAR.h` so that it can be compiled with gcc.

**Comment by Ionizing** [comment]
commit 418a0c2 has solved the problem.
I tested on Gentoo successfully with gcc7 and clang5.
